### ISSUE TITLE
Как попасть в админку?

### ISSUE THREAD

**Issue by yuri25** [Georgynet/Blog-Yii2#10]
Установил на open-server, сам сайт нормально открывается. Не могу понять как попасть в админку... У меня настроено так: домен - http://yii2blog   папка домена C:\OpenServer\domains\yii2blog\frontend\web
Не понимаю как настроить вход в backend.... Пробовал задать произвольный домен типа http://yii2blogback  и папку соответственно C:\OpenServer\domains\yii2blog\backend\web   но едет верстка и вообще это же ерунда получается назначить несуществующий домен... Посмотрел в базе нет пользователей вообще... Как админом залогиниться? Помогите пожалуйста разобраться.

**Comment by yuri25** [comment]
Попробовал авторизоваться как admin с паролем password... почему то получилось:)  Но по ссылке "Панель управления" идет переход сюда http://yii2blog/admin/site и выдает такое: Not Found (#404)
Page not found.
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you. 
Подскажите пожалуйста что я неправильно делаю.

**Comment by Georgynet** [comment]
1. Отдельный домен для админки не нужен.
2. Ссылка в админку правильная: http://yii2blog/admin/site 
3. В БД нет пользователей, поэтому для начала надо пройти регистрацию (постараюсь сегодня добавить миграцию с базовым пользователем с правами администратора).
Явно что-то криво настроено, с неверной парой логин/пароль авторизация точно не проходит.

**Comment by Georgynet** [comment]
3. Добавлен пользователь по-умолчанию. #12
