### ISSUE TITLE
Очень плохое решение ManyMany

### ISSUE THREAD

**Issue by matiosfree** [Georgynet/Blog-Yii2#11]
Очень плохое решение для связей ManyMany
https://github.com/Georgynet/Blog-Yii2/blob/master/common/models/Post.php#L189

1. Не проверяется в действительности переданы существующие tag_id
2. Если менеджер обновит заголовок\текст поста и не тронет теги, то реляции все равно удалятся и запишутся заново в таблицу.

**Comment by Georgynet** [comment]
Ничего плохого не вижу. Проверять каждую запись или удалить все, а потом записать новые - это палка о двух концах, т. к. если часть связей будет удалена, а часть добавлена, это повлечёт за собой поиск разницы, удаление и записать, что по сути равносильно.

По пункту 1: сохранение данных не произойдёт если передать несуществующие tag_id, т. к. промежуточная таблица содержит FK, и высветится ошибка.

На счёт 2-го пункта согласен - по хорошему надо бы проверить, изменялись ли связи. Если изменений не было, то и не производить перезапись.

**Comment by matiosfree** [comment]
По пункту 1: А если это бизнес-приложение, а теги (в лучшем случае, в худшем - клиенты) будут переданы чужие? Так ведь можно и себе чужие теги (клиентов) приписать.

**Comment by Georgynet** [comment]
Вы пытаетесь изменить задачу, решаемую данным приложением. У нас не бизнес приложение, а теги - не клиенты. А следовательно и ограничений на привязку Тегов к Постам нету. Не надо создавать искусственно проблему, которую блог не призван решать. Если у вас стоит задача ограничить круг привязываемых тегов - так сделайте необходимые валидаторы.
