### ISSUE TITLE
Пагинация в категориях

### ISSUE THREAD

**Issue by skvarovski** [Georgynet/Blog-Yii2#13]
Добрый день, 
хороший шаблон блога, если вы не забросили - реализуйте пагинацию в категориях.

**Comment by Georgynet** [comment]
Проект не забросил - добавлю пагинацию постов.

**Comment by Georgynet** [comment]
@skvarovski Проект не забросил - добавлю пагинацию постов.

**Comment by Georgynet** [comment]
Количество выводимых постов настраивается в конфиге: `/frontend/config/params-local.php`
```php
return [
    'pageSize' => 2
];
```
